### ISSUE TITLE
nuget package update

### ISSUE THREAD

**Issue by lancejt** [Guidelinetech/cocoon-orm#10]
I vastly prefer to use nuget to pull in packages rather than having to pull them from repositories. Can we get a nuget update to pull in the latest changes? 

I was testing the ORM for use and do like the simplicity of it. But the version currently in nuget does not return correctly for the execute methods. Everything seems to be treated as scalar.

**Comment by rhett-thompson** [comment]
I've updated the nuget package - been awhile since the last update.

**Comment by lancejt** [comment]
Thanks for the quick turnaround.
